---
    - hosts: localhost
      become: true

      tasks:
        - name: Install aptitude using apt
          apt: name=aptitude state=latest update_cache=yes force_apt_get=yes
    
        - name: Install required system packages
          apt: name={{ item }} state=latest update_cache=yes
          loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'gnupg-agent', 'locales-all', 'default-jdk']
    
        - name: Add Docker GPG apt Key
          apt_key:
            url: https://download.docker.com/linux/debian/gpg
            state: present
    
        - name: Add Docker Repository
          apt_repository:
            repo: deb https://download.docker.com/linux/debian buster stable
            state: present
    
        - name: Install docker-ce and docker-compose
          apt: update_cache=yes name={{ item }} state=latest
          loop: ['docker-ce','docker-compose']
    
        - name: Install Docker Module for Python
          pip:
            name: docker

        - name: Add the user 'admin' to 'docker' group
          user:
            name: admin
            groups: docker
            append: yes

        - name: Start service docker, if not started
          service:
            name: docker
            state: started
        
        # Jenkins installation
        - name: Add Jenkins GPG apt Key
          apt_key:
            url: https://pkg.jenkins.io/debian/jenkins.io.key
            state: present

        - name: Add Jenkins debain repository into sources list
          apt_repository:
            repo: deb http://pkg.jenkins.io/debian-stable binary/
            state: present

        - name: Install Jenkins
          apt: update_cache=yes name=jenkins state=latest

        - name: Add the user 'jenkins' to 'docker' group
          user:
            name: jenkins
            groups: docker
            append: yes

        - name: Start Jenkins
          service:
            name: jenkins
            state: started
            enabled: yes
